### ISSUE TITLE
Should call validateaddress on BitcoinNodeWalletProvider

### ISSUE THREAD

**Issue by matthewjablack** [liquality/chainabstractionlayer#199]
Currently the `BitcoinNodeWalletProvider` does not provide `publicKey`, `derivationPath` or `index`. Should call `validateaddress` on the node to get this info. 

https://github.com/liquality/chainabstractionlayer/blob/dev/packages/bitcoin-node-wallet-provider/lib/BitcoinNodeWalletProvider.js#L59

**Comment by kraikov** [comment]
CAL migrated to Chainify
