### ISSUE TITLE
regeneratorRuntime error when using ledger packages in chrome extension`

### ISSUE THREAD

**Issue by matthewjablack** [liquality/chainabstractionlayer#209]
Currently, including any `ledger` packages from CAL in a chrome extension, will return the following `regeneratorRuntime` error. 

![image (3)](https://user-images.githubusercontent.com/5362629/64734555-d7215b00-d4b4-11e9-990f-5b48051f3dad.png)

Not including any ledger packages solves this problem, but `webusb` and `ledger` packages should be usable. 

Also this is problematic for users that include `@liquality/bundle` as they may run into this error, not realizing that they should instead only include the necessary packages to stop this error from occurring.

**Comment by kraikov** [comment]
CAL migrated to Chainify
