### ISSUE TITLE
Errors thrown when using webpack 3 or lower

### ISSUE THREAD

**Issue by JesseAbram** [liquality/chainabstractionlayer#211]
Just something I found that I thought was worthwhile to log. With the default webpack 3 setup this error get thrown when importing into a project. 

![image](https://user-images.githubusercontent.com/33698952/64818513-36956e80-d57a-11e9-858b-44c38f32ed1a.png)

It is fixed by using this[ webpack addon ](https://github.com/alangpierce/sucrase/tree/master/integrations/webpack-object-rest-spread-plugin) which is natively included in webpack 4.

**Comment by kraikov** [comment]
CAL migrated to Chainify
