### ISSUE TITLE
Where is the HTLC ethereum contract?

### ISSUE THREAD

**Issue by kigawas** [liquality/chainabstractionlayer#224]
I saw a contract [here](https://github.com/liquality/chainabstractionlayer/blob/dev/packages/ethereum-erc20-swap-provider/contracts/HTLC.sol), but it looks different from [createSwapScript](https://github.com/liquality/chainabstractionlayer/blob/dev/packages/ethereum-swap-provider/lib/EthereumSwapProvider.js#L24)

There is also an [EIP](https://github.com/ethereum/EIPs/issues/1631), but I'm not sure whether they are same or not

**Comment by gr0kchain** [comment]
Hi @kigawas. In an effort to reduce the gas costs on Ethereum, we've implemented a EVM byte code version. The solidity version is for legibility as conveyed in EIP1630
