### ISSUE TITLE
Issue about examples in chainabstractionlayer

### ISSUE THREAD

**Issue by gdhucoder** [liquality/chainabstractionlayer#235]
I want to try the swap function. When I use the examples in chainabstractionlayer at `https://github.com/liquality/chainabstractionlayer/tree/dev/examples` .

`MateMaskProvider.js `throws an error: `invalid MetaMaskProvider`.
I don't have a clue how to slove this problem.

## Pre-requisites 
- [x] I looked through both open and closed issues and did not find an existing problem.
- [x] code: use chainabstractionlayer **branch dev**
- [x] bitcoin private network installed
- [x] ethereum private network installed
- [x] web3.js v1.2.2 installed
- [x] MetaMask 7.7.1
- [x] Linux 16.04 
- [x] Chrome Version 78.0.3904.108 (Official Build) (64-bit)

## Description
When trying these examples, for example,  `examples/browser/ethereum/metamask.html`，the html file does not work as I expcected.

## Expected Behavior
The `examples/browser/ethereum/metamask.html` files works fine.

## Actual Behavior
`MateMaskProvider.js `throws an error: `invalid MetaMaskProvider`.

## Steps to Reproduce

1. start bitcoin private network
2. start ethereum private network
3. open `examples/browser/ethereum/metamask.html` in Chrome
4. `MateMaskProvider.js `throws an error: `invalid MetaMaskProvider`

```js
export default class MetaMaskProvider extends WalletProvider {
  constructor (metamaskProvider, network) {
    super(network)
    if (!isFunction(metamaskProvider.sendAsync)) {
      throw new Error('Invalid MetaMask Provider')
    }
    this._metamaskProvider = metamaskProvider
    this._network = network
  }
```
![error](https://user-images.githubusercontent.com/24959965/70882853-02fc3180-200c-11ea-9a6a-840f14f80626.png)

**Comment by harshjv** [comment]
Hello @gdhucoder, thank you for reporting the error!

However, this issue is unrelated to the library. MetaMask doesn't inject web3 on `file://`. (Ref: https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#globe_with_meridians-https---web-server-required)

Can you please serve the file over HTTP? You can use https://www.npmjs.com/package/serve.

```
cd chainabstractionlayer
serve .
```

Then open http://localhost:5000/examples/browser/ethereum/metamask.html

🍻
