### ISSUE TITLE
Create EthereumMementoSwapFindProvider

### ISSUE THREAD

**Issue by monokh** [liquality/chainabstractionlayer#236]
Using the api and blockscanning for finding swap transactions is too resource heavy when relying on a remote node. As a workaround, the memento api can be used to reduce this burden.

The contract address for the swap can be generated and watched for the swap transactions using the memento API.

Include tests

**Comment by monokh** [comment]
Decided against generating contract address. As it depends on sender and nonce only - the nonce needs to be iterated through. Meaning there needs to be a call to check each contract address from transactionCount(address) until 0. This could potentially produces many calls -one for each transaction after the contract was created. Especially problematic if the find function is used for historical swaps.

Getting all transactions from the sender is 1 call and can be filtered through for the contract creation.

**Comment by harshjv** [comment]
Related to #234
