### ISSUE TITLE
getReceivedByAddress missing from BitcoinEsploraApiProvider

### ISSUE THREAD

**Issue by matthewjablack** [liquality/chainabstractionlayer#362]
If you try to call `isAddressUsed` in `BitcoinEsploraApiProvider` and error will come up if you don't also include `BitcoinRpcProvider` since `getReceivedByAddress` is not implemented

https://github.com/liquality/chainabstractionlayer/blob/dev/packages/bitcoin-esplora-api-provider/lib/BitcoinEsploraApiProvider.js#L45

**Comment by kraikov** [comment]
CAL migrated to Chainify
