### ISSUE TITLE
Please use another bitcoin fees API provider

### ISSUE THREAD

**Issue by bretton** [liquality/chainabstractionlayer#401]
Hi, I'm not familiar with your project. I did a search for `https://bitcoinfees.earn.com/api/v1/fees/recommended` and am alerting projects using this API to inaccurate & old data.

An up-to-date API with accurate data would be `https://mempool.space/api/v1/fees/recommended` or some alternative.

https://github.com/liquality/chainabstractionlayer/blob/d8b94087515b656e2d487b9c26704d5bef227413/packages/bitcoin-earn-fee-provider/lib/BitcoinEarnFeeProvider.ts

**Comment by monokh** [comment]
Thank you. We already pointed our usage to mempool.space but we will remove the code now
